---

- name: "Vlan configuration for Cisco Switches using Jinja2"
  hosts: ciscosw
  connection: network_cli

  tasks:
    - name: "Vlan configuration on IOS devices"
      cisco.ios.ios_config:
        src: "{{ ansible_network_os }}-vlans.j2"
      register: cisco_output

    - name: "Print the output"
      debug:
        msg: "{{ cisco_output }}"
